//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public double Price { get; set; }
    }
}
