//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineCourse : Cours
    {
        public Nullable<bool> SelfPaced { get; set; }
    }
}
