//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Designer_TPT_Inheritance
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabCourse : Course
    {
        public string Location { get; set; }
    }
}
