//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecificRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterNewPicture
    {
        public int New_ID { get; set; }
        public string PictureDescription { get; set; }
        public string PictureLocation { get; set; }
    
        public virtual CenterNew CenterNew { get; set; }
    }
}
